### ISSUE TITLE
JRuby issue in jenkins plugin

### ISSUE THREAD

**Issue by rmpestano** [rmpestano/living-documentation-plugin#1]
The error below is raised when AsciidoctorJ tries to [load JRuby]
(https://github.com/rmpestano/cukedoctor-jenkins-plugin/blob/master/src/main/java/com/github/cukedoctor/jenkins/CukedoctorPublisher.java#L175):

ERROR: Publisher com.github.cukedoctor.jenkins.CukedoctorPublisher aborted due to exception
java.lang.NoSuchMethodError: jnr.constants.platform.OpenFlags.defined()Z
	at org.jruby.RubyFile.createFileClass(RubyFile.java:149)
	at org.jruby.Ruby.initCore(Ruby.java:1545)
	at org.jruby.Ruby.bootstrap(Ruby.java:1330)
	at org.jruby.Ruby.init(Ruby.java:1221)
	at org.jruby.Ruby.newInstance(Ruby.java:330)
	at org.jruby.javasupport.JavaEmbedUtils.initialize(JavaEmbedUtils.java:79)
	at org.asciidoctor.internal.JRubyAsciidoctor.createJRubyAsciidoctorInstance(JRubyAsciidoctor.java:126)
	at org.asciidoctor.internal.JRubyAsciidoctor.create(JRubyAsciidoctor.java:57)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:668)
	at com.github.cukedoctor.jenkins.CukedoctorPublisher.execute(CukedoctorPublisher.java:175)
	at com.github.cukedoctor.jenkins.CukedoctorPublisher.perform(CukedoctorPublisher.java:156)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
	at hudson.model.Run.execute(Run.java:1784)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Finished: FAILURE

Looks like its related to: https://github.com/jruby/jruby/issues/3332

Tried with all jruby-complete versions and multiple jenkins runtime versions.

Steps to reproduce the issue: 

* Setup [jenkins settings.xml](https://wiki.jenkins-ci.org/display/JENKINS/Plugin+tutorial#Plugintutorial-SettingUpEnvironment) 
* run the following maven command in this project root:
```
mvn hpi-run
```
* configure jenkins [git plugin](https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin);
* use [cukedoctor-jenkins-plugin](https://github.com/rmpestano/cukedoctor-jenkins-plugin.git) git repository (it has cucumber json output files);
* Living documentation plugin should alredy be installed (if you ran hpi:run)

See configuration page:
![config](https://cloud.githubusercontent.com/assets/1592273/13909345/23e2989a-eef0-11e5-8dd2-6a6499f8b399.png)

**Comment by rmpestano** [comment]
downgraded jruby to 1.7.13 and used plugin classloader to create asciidoctor instance solved the issue on windows and linux.
